// pages/about.tsx
import Head from 'next/head';
import Link from 'next/link';

const faqItems = [
  {
    question: "What is the Royalty Music Platform?",
    answer: "It's a decentralized platform allowing artists to tokenize their music royalty rights as NFTs. Fans and investors can purchase these NFTs to earn a share of the royalties generated by the music, primarily through streaming."
  },
  {
    question: "How are artists rated?",
    answer: "Artists are dynamically rated on a scale of 2.5–5.0 based on various performance metrics like streaming data, fan engagement, and market trends. This rating, along with a risk metric, helps investors make informed decisions."
  },
  {
    question: "What are Fractional Royalty Rights?",
    answer: "We use ERC-1155 Non-Fungible Tokens (NFTs) to represent fractional ownership of music rights. This means you can own a small piece of a song's royalty stream, making it accessible to a wider range of investors."
  },
  {
    question: "How are royalties distributed?",
    answer: "Smart contracts on the Avalanche C-Chain handle royalty distributions automatically. When royalties are collected (simulated or from real streams), they are distributed proportionally to NFT holders who have staked their tokens."
  },
  {
    question: "What is staking in this context?",
    answer: "By 'staking' your royalty NFTs, you actively participate in earning. Staked NFTs are eligible for royalty payouts. The more shares you stake, the larger your portion of the distributed royalties."
  },
  {
    question: "What technology is used?",
    answer: "The frontend is built with Next.js, React, and Tailwind CSS. Smart contracts are written in Solidity and deployed on the Avalanche C-Chain. We use Web3.js/Ethers.js for blockchain interactions and plan to integrate with Core Wallet SDK."
  },
  {
    question: "Is this platform secure?",
    answer: "Security is a top priority. Smart contracts will undergo audits. We plan to use multi-signature wallets for critical operations and integrate with oracles for reliable real-world data feeds. KYC/AML procedures are also part of our long-term compliance strategy."
  }
];

export default function AboutPage() {
  return (
    <>
      <Head>
        <title>About Us | Royalty Music Platform</title>
        <meta name="description" content="Learn more about the Royalty Music Platform, our mission, technology, and how we're changing the music industry." />
      </Head>

      <div className="container mx-auto px-4 py-8">
        {/* Hero Section */}
        <section className="text-center py-12 bg-slate-800 rounded-lg shadow-xl mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-primary-gold mb-4">About Royalty Music Platform</h1>
          <p className="text-lg md:text-xl text-secondary-white max-w-3xl mx-auto">
            Empowering artists and fans through transparent, decentralized music royalty sharing.
          </p>
        </section>

        {/* Mission and Vision Section */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-secondary-light-blue mb-6 text-center md:text-left">Our Mission & Vision</h2>
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div className="bg-primary-dark-blue-gray p-6 rounded-lg shadow-lg">
              <h3 className="text-2xl font-semibold text-primary-gold mb-3">Mission</h3>
              <p className="text-secondary-white leading-relaxed">
                To provide a fair, transparent, and efficient platform for artists to fund their careers by tokenizing future royalty streams, and for fans and investors to directly support artists and share in their success.
              </p>
            </div>
            <div className="bg-primary-dark-blue-gray p-6 rounded-lg shadow-lg">
              <h3 className="text-2xl font-semibold text-primary-gold mb-3">Vision</h3>
              <p className="text-secondary-white leading-relaxed">
                To become the leading decentralized solution for music royalty investment and distribution, fostering a closer connection between artists and their audience, and unlocking new revenue models for the music industry through blockchain technology.
              </p>
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-secondary-light-blue mb-6 text-center">How It Works</h2>
          <div className="space-y-6">
            <div className="bg-slate-800 p-6 rounded-lg shadow-md">
                <h3 className="text-xl font-semibold text-primary-gold mb-2">1. Artist Onboarding & NFT Minting</h3>
                <p className="text-gray-300">Artists connect their wallets, define their royalty-sharing NFTs (ERC-1155), and set investment targets. Each NFT represents a fraction of future royalty rights for specific musical works.</p>
            </div>
            <div className="bg-slate-800 p-6 rounded-lg shadow-md">
                <h3 className="text-xl font-semibold text-primary-gold mb-2">2. Fan Investment & Staking</h3>
                <p className="text-gray-300">Fans and investors browse artist profiles and purchase fractional NFTs. By staking these NFTs on our platform, they become eligible to earn proportional shares of distributed royalties.</p>
            </div>
            <div className="bg-slate-800 p-6 rounded-lg shadow-md">
                <h3 className="text-xl font-semibold text-primary-gold mb-2">3. Royalty Distribution</h3>
                <p className="text-gray-300">Simulated (and eventually real) streaming data is processed. Royalties are then automatically calculated and distributed by smart contracts to staked NFT holders. Users can claim their earnings at any time.</p>
            </div>
             <div className="bg-slate-800 p-6 rounded-lg shadow-md">
                <h3 className="text-xl font-semibold text-primary-gold mb-2">4. Secondary Market Trading</h3>
                <p className="text-gray-300">Users can buy and sell their fractional royalty NFTs on a secondary marketplace, providing liquidity and price discovery for these unique assets.</p>
            </div>
          </div>
        </section>

        {/* Technology Section */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-secondary-light-blue mb-6 text-center md:text-left">Technology We Use</h2>
          <div className="bg-primary-dark-blue-gray p-8 rounded-lg shadow-lg">
            <ul className="list-disc list-inside space-y-3 text-secondary-white">
              <li><strong>Frontend:</strong> Next.js, React, Tailwind CSS for a modern, responsive user interface.</li>
              <li><strong>Blockchain Interaction:</strong> Web3.js / Ethers.js for connecting to the Avalanche network. Integration with Core Wallet SDK is planned.</li>
              <li><strong>Smart Contracts:</strong> Written in Solidity and deployed on the Avalanche C-Chain. Key contracts include `RoyaltyNFT.sol` (ERC-1155), `RoyaltyStaking.sol`, and `StreamingSimulator.sol` (for testing).</li>
              <li><strong>Deployment:</strong> Frontend hosted on Vercel. Smart contracts on Avalanche Testnet (initially) and Mainnet.</li>
              <li><strong>Oracles (Planned):</strong> For fetching real-time streaming data and other external inputs securely.</li>
            </ul>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-secondary-light-blue mb-8 text-center">Frequently Asked Questions</h2>
          <div className="space-y-6 max-w-3xl mx-auto">
            {faqItems.map((item, index) => (
              <details key={index} className="bg-slate-800 p-4 rounded-lg shadow group">
                <summary className="font-semibold text-primary-gold text-lg cursor-pointer list-none flex justify-between items-center group-open:text-secondary-light-blue">
                  {item.question}
                  <span className="text-primary-gold group-open:rotate-90 transform transition-transform duration-200 ml-2">&#9656;</span>
                </summary>
                <p className="text-gray-300 mt-3 leading-relaxed">{item.answer}</p>
              </details>
            ))}
          </div>
        </section>

        {/* Call to Action */}
        <section className="text-center py-10">
          <h2 className="text-2xl font-bold text-primary-gold mb-4">Ready to Join the Revolution?</h2>
          <p className="text-secondary-white mb-6 max-w-xl mx-auto">
            Explore artists, invest in music royalties, or learn more about how to get started.
          </p>
          <div className="space-x-0 md:space-x-4 space-y-4 md:space-y-0">
            <Link href="/" legacyBehavior>
              <a className="bg-primary-gold hover:bg-yellow-500 text-primary-dark-blue-gray font-bold py-3 px-6 rounded-lg text-lg transition-colors">
                Explore Artists
              </a>
            </Link>
            <Link href="/staking" legacyBehavior>
              <a className="bg-secondary-light-blue hover:bg-blue-500 text-white font-bold py-3 px-6 rounded-lg text-lg transition-colors">
                Start Staking
              </a>
            </Link>
          </div>
        </section>
      </div>
    </>
  );
}
